# Generated by Django 2.2.7 on 2019-12-29 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('thumbnail_image', models.ImageField(blank=True, upload_to='Image/books/')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('unit_name', models.CharField(max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('translated_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='Image/words/')),
                ('sound', models.FileField(blank=True, upload_to='Audio')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening', models.BooleanField()),
                ('speaking', models.BooleanField()),
                ('reading', models.BooleanField()),
                ('writing', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.AppUser')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.Word')),
            ],
        ),
    ]
